global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter_target'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.11:9100', '192.168.100.12:9100']
